"""empty message

Revision ID: d7cb581880bf
Revises: ab486cbf4eb4
Create Date: 2019-12-17 18:30:42.285791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cb581880bf'
down_revision = 'ab486cbf4eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_status')
    # ### end Alembic commands ###
