"""empty message

Revision ID: f575b49370e9
Revises: 9327f40e9976
Create Date: 2019-12-17 21:19:46.747789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f575b49370e9'
down_revision = '9327f40e9976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('client_secret', table_name='clients')
    op.create_unique_constraint(None, 'clients', ['client_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_index('client_secret', 'clients', ['client_secret'], unique=True)
    # ### end Alembic commands ###
